import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="font-sans grid grid-rows-[20px_1fr_20px] items-center justify-items-center min-h-screen">
          <main className="flex flex-col  row-start-2 items-center sm:items-start">
            <div className="container min-w-200">
              <p><Link href="/">Home</Link> | <Link href="/about">About</Link> | <Link href="/articles">Articles</Link> | <Link href="/contact">Contact</Link> </p>
              {children}
            </div>
          </main>
        </div>
      </body>
    </html>
  );
}
